language: node_js
node_js:
- '5'
services:
- redis
branches:
  only:
  - /^v[0-9]/
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: DWufvIJStIzW9xCV94pNw03shCdhJpFiUF/XJCQsnAga4OFEKm58uajr8wJR1P3QqCUE2Po0PfSFiLFp0d2LaULY6Xsj+gJMOL6M85/mxCwSR0X+Qe+k/sNtBMuc9CzFYwYn+V1/rLAYxe/wKbj4vbmEh0dB17rXwiSNb4a9qpLVFBiddBBhk/6/EipOpJjunXO0dps0EK4dxyS6GaqSGfZ3eC3BZrZe6Noquid+QUnFRg+RHnuo6y6gmMAGVfimdXTnY9CjN6AftlkdARdeHBTTRfbgwVi8ePyWDOKHAN/hNSyQwfSiqEMLxAUp0Wfa9Sn6+7bNRxlcXw9eOIiyX9QNCmZCmJBK1o1asyb3el2bDp3MhHfLnikdZm6V/rAFt0BoFdH+8uc5Q9aI1ZxnWnzmKAMB6mOj9+Ev8JIqgLlrobvbn82wMCQIKN8RaKRlkfMqW6PB49KVbA2xp7XIHV+HIfaqk2KBrl+QQ3EfNuAWLwcstoL3fwvHiNzEzU548O9HmaHUxIHFDXPjzqXaFMFjGiCT1WEim1FEDHA2W3kkwI1dl2peqksjZGOF20bKXoZViTG3wA5A5snOh0VlAKWRYNRdP2lwC8rGHHQNd8ck0rJY40BD2wIFWFnEVEgJtOnleaKxXF/v5F1iBpIEvfWbVBwgvqAIhUAQnxJ5tpg=
  on:
    tags: true
    branches: true
